- .github/CODEOWNERS
- requirements.txt
- setup.py
> Change code owners

- .github/actions/install-finance/action.yml
- .github/actions/install-libraries/action.yml
- qiskit_finance/applications/ising/portfolio.py
- qiskit_finance/applications/ising/portfolio_diversification.py
- test/test_portfolio_diversification.py
> Fix Deprecation msgs and Add cplex to CI

- .github/workflows/main.yml
- qiskit_finance/applications/ising/portfolio.py
- qiskit_finance/data_providers/_base_data_provider.py
- test/test_european_call_expected_value.py
- test/test_portfolio.py
- test/test_portfolio_diversification.py
> Change aqua_globals to algorithm_globals

- qiskit_finance/applications/ising/portfolio.py
- test/test_data_providers.py
> Remove DeprecationWarning of np.bool

- .github/workflows/main.yml
- qiskit_finance/applications/fixed_income_expected_value.py
- qiskit_finance/applications/ising/portfolio_diversification.py
- qiskit_finance/data_providers/_base_data_provider.py
- tox.ini
> Run mypy on python 3.7

- .github/actions/install-master-dependencies/action.yml
- .github/workflows/main.yml
- requirements-dev.txt
- tox.ini
> Fix cvxpy CI install error on python 3.7

- .github/actions/install-finance/action.yml
- .github/workflows/main.yml
Tutorials fail randomly due to Jupyter bug: jupyter/jupyter_client#541
This PR disables parallelism on tutorials by setting env: QISKIT_PARALLEL=False
Also, the CI has been streamlined.
> Disable parallelism on tutorials job, refactor CI

- constraints.txt
- requirements-dev.txt
Upgrades pylint minimum version following Qiskit/qiskit-terra#5630
Updates constraints.txt to be equivalent to qiskit-terra
> Upgrade to pylint 2.7

- MANIFEST.in
- setup.py
- test/applications/ising/test_portfolio.py
- test/data_providers/test_data_providers.py
- tutorials/01_portfolio_optimization.ipynb
> Fix Yahoo data unit test

- setup.py
> Change setup.py setuptools from find_namespace_packages to find_packages

- docs/conf.py
> Fix tutorials notes link

- .github/workflows/main.yml
> [Stable] Make sure CI gets Qiskit dependencies from pypi on stable (#33)

- .github/actions/install-main-dependencies/action.yml
- .github/workflows/main.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/tutorials/02_portfolio_diversification.ipynb
- qiskit_finance/circuit/library/probability_distributions/lognormal.py
- qiskit_finance/data_providers/_base_data_provider.py
- qiskit_finance/data_providers/data_on_demand_provider.py
- qiskit_finance/data_providers/exchange_data_provider.py
- qiskit_finance/data_providers/wikipedia_data_provider.py
- qiskit_finance/data_providers/yahoo_data_provider.py
- qiskit_finance/version.py
- tox.ini
Related to Qiskit/qiskit-terra#6221
More details at: https://github.com/github/renaming
Forks should also rename the default branch from master to main in Github settings.
After renaming your fork in Github, you should issue the following commands locally:
```
git checkout master
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
git remote prune origin
```
> Prepare for renaming default branch to main

- .github/actions/install-main-dependencies/action.yml
- .github/workflows/main.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/tutorials/02_portfolio_diversification.ipynb
- qiskit_finance/circuit/library/probability_distributions/lognormal.py
- qiskit_finance/data_providers/_base_data_provider.py
- qiskit_finance/data_providers/data_on_demand_provider.py
- qiskit_finance/data_providers/exchange_data_provider.py
- qiskit_finance/data_providers/wikipedia_data_provider.py
- qiskit_finance/data_providers/yahoo_data_provider.py
- qiskit_finance/version.py
- tox.ini
* Prepare for renaming default branch to main
Backport of #36
> [Stable] Prepare for renaming default branch to main (#36)

- qiskit_finance/version.py
- tools/check_copyright.py
Latest pylint release introduced new test that are causing the CI to fail on main and stable.
> Fix lint msgs caused by latest pylint release

- .github/actions/run-tests/action.yml
- .github/workflows/main.yml
- test/__init__.py
- test/data_providers/test_data_providers.py
- test/finance_test_case.py
> Add 'run_slow' handling and requires_extra_library unit test decorator

- .github/actions/run-tests/action.yml
>  Print PendingDeprecation warnings in the CI

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
> [Stable] Fix sphinx CI Error (#47)

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- docs/conf.py
- docs/custom_directives.py
- docs/getting_started.rst
- docs/index.rst
- requirements-dev.txt
Add a Getting Started documentation page that 'augments' the main one of Qiskit by providing additional installation information etc specific to this application.
> Add Getting Started Documentation

- README.md
The bib file link returns a "page not found" error. This PR fixes it.
> Fixed link to bib file in `README`

- requirements-dev.txt
Install types-certifi to comply with latest mypy version
>  Install types-certifi on requirements-dev.txt 

- .github/workflows/main.yml
- .pylintdict
- .pylintrc
- Makefile
- requirements-dev.txt
- tools/verify_headers.py
- tox.ini
Equivalent to Qiskit/qiskit-machine-learning#133
> Move away from using pylint header plugin

- .github/workflows/main.yml
> [Stable] Streamline CI (#78)

- README.md
Replaced a link to the old tutorials to the new ones.
> Fix tutorial link in readme.md

- qiskit_finance/data_providers/exchange_data_provider.py
- qiskit_finance/data_providers/wikipedia_data_provider.py
- qiskit_finance/version.py
- tools/extract_deprecation.py
- tools/generate_spell_dict.py
> Fix lint errors

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- Makefile
> [Stable] Fix docs release notes search (#96)

- test/circuit/test_european_call_delta_objective.py
- test/circuit/test_european_call_pricing_objective.py
> Fix unit test failure due to new Aer

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- CODE_OF_CONDUCT.md
- README.md
- setup.py
- tools/ignore_untagged_notes.sh
> Improve project setup long-description & Ignore untagged release notes on docs.upload

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- CODE_OF_CONDUCT.md
- README.md
- setup.py
- tools/ignore_untagged_notes.sh
> [Stable] Improve project setup long-description & Ignore untagged release notes on docs.upload (#100)

- .pylintrc
- README.md
- qiskit_finance/applications/optimization/portfolio_diversification.py
- qiskit_finance/circuit/library/probability_distributions/normal.py
- qiskit_finance/data_providers/data_on_demand_provider.py
- qiskit_finance/data_providers/exchange_data_provider.py
- qiskit_finance/data_providers/wikipedia_data_provider.py
- qiskit_finance/data_providers/yahoo_data_provider.py
- qiskit_finance/version.py
- test/applications/test_portfolio_diversification.py
- test/circuit/test_european_call_delta_objective.py
- test/circuit/test_european_call_pricing_objective.py
- test/circuit/test_fixed_income_pricing_objective.py
- test/data_providers/test_data_providers.py
- test/finance_test_case.py
- test/test_readme_sample.py
- tools/check_copyright.py
- tools/extract_deprecation.py
- tools/generate_spell_dict.py
- tools/verify_headers.py
> Re-enable lint f-string check

- tools/deploy_translatable_strings.sh
Related to https://github.com/Qiskit/qiskit-optimization/pull/261
> Fixing the translations script that was breaking the translated docs publish build

- docs/tutorials/00_amplitude_estimation.ipynb
> Update 00_amplitude_estimation.ipynb - Backport from Stable (#109)

- test/data_providers/test_data_providers.py
> Fix Yahoo test case

- .github/workflows/main.yml
- .mergify.yml
> Fix mergify automerge

- .github/workflows/main.yml
- constraints.txt
- releasenotes/notes/drop-python3.6-support-dbab639be0832d2c.yaml
- setup.py
- tox.ini
> Drop support for Python 3.6

- mypy.ini
- qiskit_finance/circuit/library/probability_distributions/lognormal.py
Following Qiskit/qiskit-optimization#180
> Enable some mypy options

- qiskit_finance/data_providers/_base_data_provider.py
numpy 1.22.0 released for python > 3.7 added mypy errors.
Errors fixed in this PR
> Fix mypy errors created with latest numpy

- .github/actions/install-finance/action.yml
- .github/actions/install-main-dependencies/action.yml
- .github/actions/run-tests/action.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- pyproject.toml
- releasenotes/notes/add-python310-support-c0771fca614b0cde.yaml
- setup.py
- tox.ini
Following Qiskit/qiskit-terra#7102
IMPORTANT:
Terra is backporting this. Once they release it to pypi, I will backport it as well. Do not backport before they release otherwise it will fail. The stable CI gets Terra from Pypi.
> Add support for Python 3.10

- .pylintdict
- docs/apidocs/qiskit_finance.circuit.library.rst
- docs/apidocs/qiskit_finance.circuit.rst
- qiskit_finance/__init__.py
- qiskit_finance/circuit/__init__.py
- qiskit_finance/circuit/library/__init__.py
- qiskit_finance/circuit/library/payoff_functions/fixed_income_pricing_objective.py
- qiskit_finance/circuit/library/probability_distributions/lognormal.py
- qiskit_finance/circuit/library/probability_distributions/normal.py
- qiskit_finance/circuit/library/probability_distributions/uniform.py
> Add circuit library documentation

- .github/actions/install-finance/action.yml
- .github/actions/install-main-dependencies/action.yml
- .github/actions/run-tests/action.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- pyproject.toml
- releasenotes/notes/add-python310-support-c0771fca614b0cde.yaml
- setup.py
- tox.ini
> [Stable] Add support for Python 3.10

- docs/versionutils.py
Bengali Finance docs are a 100% translated and proofread. Preparing to publish those docs.
This can wait till the build https://github.com/qiskit-community/qiskit-translations/actions/runs/1884635447 is successful
> Preparing to publish Bengali docs

- qiskit_finance/data_providers/exchange_data_provider.py
- qiskit_finance/data_providers/random_data_provider.py
- qiskit_finance/data_providers/wikipedia_data_provider.py
- qiskit_finance/data_providers/yahoo_data_provider.py
- requirements.txt
- test/__init__.py
- test/circuit/test_european_call_delta_objective.py
- test/circuit/test_european_call_pricing_objective.py
- test/circuit/test_fixed_income_pricing_objective.py
- test/data_providers/test_data_providers.py
- test/finance_test_case.py
Adopt the API implemented in Qiskit/qiskit-terra#7525
> Adopt lazy imports from Terra

- MANIFEST.in
- qiskit_finance/py.typed
> Add py.typed marker

- .github/workflows/main.yml
- requirements-dev.txt
> Pin pylint to < 2.14.0

- docs/index.rst
> Add overview to docs

- test/circuit/test_european_call_delta_objective.py
- test/circuit/test_european_call_pricing_objective.py
- test/circuit/test_fixed_income_pricing_objective.py
Related to Qiskit/qiskit-terra#5089
> Fix Aer Deprecate Messages

- .github/workflows/main.yml
- constraints.txt
- releasenotes/notes/drop-python3.6-support-dbab639be0832d2c.yaml
- setup.py
- tox.ini
> [Stable] Drop support for Python 3.6 (#121)

- Makefile
- tools/find_stray_release_notes.py
- tox.ini
Following the same check added to Terra at Qiskit/qiskit-terra#8320
> Script to check if reno release note was committed to the wrong place

- docs/conf.py
- qiskit_finance/applications/__init__.py
- qiskit_finance/applications/estimation/__init__.py
- requirements.txt
Similar to Qiskit/qiskit-nature#783
> Enable inter-documentation links to be clickable

- .github/actions/install-main-dependencies/action.yml
- .github/workflows/deploy-code.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
Following advice from Github, update actions to latest versions
> Update Github Actions versions

- .github/workflows/deploy-code.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- test/data_providers/test_data_providers.py
Update GIthub actions setup-python to latest version to remove deprecation msgs.
Update Yahoo unit test to use the same tickers and dates as tutorial.
> Update ci setup-python and yahoo unit test

- test/data_providers/test_data_providers.py
> Correct Yahoo provider unit test result

- requirements-dev.txt
> Adjust networkx requirements to match Optimization

- docs/getting_started.rst
Issue was found by a translator
> Fix a sentence in getting_started.rst

- docs/conf.py
With the change to publishing many of the qiskit docs in `ecosystem` this updates the mapping url for `optimization` accordingly.
Since this is now the correct url, I also marked it for stable backport, for any docs updates we do, though I imagine the redirect on the former url will be in place for some time.
> Update intersphinx mappings

- test/data_providers/test_data_providers.py
CI is failing unit testing for yahoo data provider and has been in the scheduled CI for the past 5 days. This updates the unit test.
> Update yahoo data provider unit test

- .github/workflows/main.yml
This repository was recently moved from `qiskit` to `qiskit-community`, but CI was not updated.
> Fix CI not running due to qiskit-community migration

- test/data_providers/test_data_providers.py
The merge commit for #289 failed as did last night's timed CI with a failure on the yahoo data provider. I amended the test - this seems to happen, be needed, on occasions - may they prune down historical data which changes things a little.
> Update data provider unit test

- releasenotes/notes/0.4-prelude-e12d8c852c35b7d4.yaml
> Add prelude of v0.4

- CONTRIBUTING.md
- docs/getting_started.rst
- setup.py
Closes https://github.com/qiskit-community/qiskit-finance/issues/322.
> Remove remaining qiskit.org links

- test/data_providers/test_data_providers.py
Updated the reference values for the test. As the test notes itself
```
```
Needs to be backported so stable branch passes tests too there.
> Fix test_data_providers test_yahoo test
