qiskit-community/qiskit-finance

.github/actions/install-master-dependencies/action.yml, docs/conf.py
Conan downloads dependencies from JFrog Bintray that goes down sometimes. This disables Conan and installs dependencies in the CI.
=> Disable Conan on CI Aer build

pyproject.toml, qiskit_finance/applications/optimization/portfolio_diversification.py, qiskit_finance/applications/optimization/portfolio_optimization.py, qiskit_finance/circuit/library/payoff_functions/european_call_delta_objective.py, qiskit_finance/circuit/library/payoff_functions/fixed_income_pricing_objective.py, qiskit_finance/circuit/library/probability_distributions/lognormal.py, qiskit_finance/circuit/library/probability_distributions/normal.py, qiskit_finance/data_providers/_base_data_provider.py, qiskit_finance/data_providers/data_on_demand_provider.py, qiskit_finance/data_providers/exchange_data_provider.py, qiskit_finance/data_providers/random_data_provider.py, qiskit_finance/data_providers/wikipedia_data_provider.py, test/applications/test_european_call_pricing.py, test/applications/test_portfolio_diversification.py, test/applications/test_portfolio_optimization.py, test/circuit/test_european_call_delta_objective.py, test/circuit/test_european_call_pricing_objective.py, test/circuit/test_fixed_income_pricing_objective.py, test/circuit/test_probability_distributions.py, test/data_providers/test_data_providers.py, test/finance_test_case.py, test/test_readme_sample.py, tools/check_copyright.py, tools/extract_deprecation.py
Adds the missing pyproject.toml file.
Similar to Qiskit/qiskit-nature#172
=> Add missing black settings

qiskit_finance/applications/optimization/portfolio_diversification.py, qiskit_finance/applications/optimization/portfolio_optimization.py, qiskit_finance/circuit/library/probability_distributions/lognormal.py, qiskit_finance/circuit/library/probability_distributions/normal.py, requirements.txt
Resolves #58.
Updated `PortfolioOptimization` and `PortfolioDiversification` to use `from_docplex_mp()` based on the change in [Qiskit/qiskit-optimization#122](https://github.com/Qiskit/qiskit-optimization/pull/166).
Also added   `qiskit-optimization>=0.2.0` into `requirements.txt`.
=> Updated to use `from_docplex_mp` in the applications of qiskit finance

README.md, qiskit_finance/circuit/library/probability_distributions/gaussian_conditional_independence_model.py, test/circuit/test_european_call_delta_objective.py, test/circuit/test_european_call_pricing_objective.py, test/circuit/test_fixed_income_pricing_objective.py, test/test_readme_sample.py
Fixes #66
* Update deprecated `Distributions` imports
* `Distributions` were moved out of the qiskit circuit library to the circuit library here in finance. This fix changes the imports to deprecated `Distributions` in the qiskit to new `Distributions` in the qiskit-finance and solve some warnings.
=> Update deprecated `Distributions` imports (#66)

requirements.txt
Pandas 1.4.0 released on 01/22/2022 breaks Yahoo Finance library.
Pinning pandas < 1.4.0 until Yahoo Finance library gets fixed.
=> Pandas 1.4.0 breaks Yahoo Finance library

.github/actions/install-finance/action.yml, .github/actions/install-main-dependencies/action.yml, .github/actions/run-tests/action.yml, .github/workflows/main.yml
Recent CI release of Windows 2022 breaks Terra main build. Pinning to previous 2019 for now.
=> Pin Windows CI version to 2019

qiskit_finance/data_providers/exchange_data_provider.py, qiskit_finance/data_providers/random_data_provider.py, qiskit_finance/data_providers/wikipedia_data_provider.py, qiskit_finance/data_providers/yahoo_data_provider.py
Fix docstrings of data providers so the html of the API reference is correctly formatted as its not now e.g.
=> Fix data provider docstring formatting

releasenotes/notes/pandas-restriction-0965815429fd8877.yaml, requirements.txt
It should be safe to drop the restriction on the `pandas` dependency that was introduced because of #133 by using the most recent version of `yfinance`.
The bug that broke `yfinance` upon upgrading to `pandas>=1.4.0` (see #133) has been fixed in the release of version `0.1.70` (see https://github.com/ranaroussi/yfinance/releases/tag/0.1.70 and the corresponding issue https://github.com/ranaroussi/yfinance/issues/937). As such, it should be safe to drop the restriction and permit newer versions of pandas.
=> Drop `pandas` requirement restriction

qiskit_finance/data_providers/exchange_data_provider.py, qiskit_finance/data_providers/wikipedia_data_provider.py, test/circuit/test_european_call_delta_objective.py, test/circuit/test_european_call_pricing_objective.py, test/circuit/test_fixed_income_pricing_objective.py, test/data_providers/test_data_providers.py
Closes #198 
The Nasdaq Data Link tests will be skipped if token is not provided in an env.variable. Since a token is personal and not provided in the CI, the CI will always skip those tests. In case a token is provided, any error will fail the unit test.
For Wikipedia provider a token is not mandatory. In that case, any error will fail unit test unless it is a daily data usage exceeded in which case it will be skipped.
=> Skip Nasdaq Data Link test if token not provided

qiskit_finance/data_providers/yahoo_data_provider.py
Random database lock when downloading Yahoo Finance data in multithread mode.
=> Yahoo Finance download single thread to avoid database lock

docs/conf.py
This reverts a path change that was done by #244 
This change was not done on the other application repos. Without it the deploy_translatable_strings part of the deploy-docs workflow fails
```
Running Sphinx v5.3.0
Traceback (most recent call last):
File "/home/runner/work/qiskit-finance/qiskit-finance/docs/.tox/docs/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
exec(code, namespace)
File "/home/runner/work/qiskit-finance/qiskit-finance/docs/conf.py", line 37, in <module>
import qiskit_finance
ModuleNotFoundError: No module named 'qiskit_finance'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/runner/work/qiskit-finance/qiskit-finance/docs/.tox/docs/lib/python3.8/site-packages/sphinx/cmd/buil …
```
=> Revert path change in conf.py

docs/conf.py, requirements-dev.txt, tox.ini
See Qiskit/qiskit-nature#1109 for more detail.
Basically does the same three things
- Removes dependency on sphinx-autodoc-typehints
- Adds default thumbnail config as that changed in nbsphinx 0.9
- Updates tox.ini gettext section used for translatable strings due to ipykernel not being installed by default now
=> Various docs changes for CI

.github/workflows/main.yml
Most people agree that GitHub made a mistake by having forks run CI both on the fork and in the upstream repository. It wastes computing resources (which has a real environmental cost!).
If people really want to run CI in their fork, they can always modify their fork's config to revert this change.
=> Turn off CI for forks

README.md
Fixes #278
Replaced QuantumInstance usage by Sampler in README sample program.
Also updated the main description a little.
=> Update readme to use Sampler instead of now deprecated QuantumInstance

.github/actions/run-tests/action.yml, .github/workflows/deploy-code.yml, .github/workflows/main.yml, .mergify.yml, pyproject.toml, releasenotes/notes/drop_python_3_7-d90741833dc57229.yaml, setup.py, tox.ini
Qiskit has dropped support Python 3.7 and this follows suit for Finance.
=> Drop Python 3.7 support

docs/_templates/autosummary/class.rst, docs/_templates/autosummary/class_no_inherited_members.rst, qiskit_finance/applications/__init__.py, qiskit_finance/circuit/__init__.py, qiskit_finance/circuit/library/__init__.py, qiskit_finance/data_providers/__init__.py
Moved all the methods and attributes into class pages to speed up the building process of the documentation with the new ecosystem sphinx theme for consistency with how the other app repo docs is now done e.g. qiskit-community/qiskit-optimization#563
I also updated heading levels in init pages so that only one link appears in the left sidebar for each page (rather than multiple) as was also done in the other app repos.
The init file in .circuit has a title Circuit Library which was the very same as that used in .circuit.library so I removed the library part so that sidebar elements are unique (otherwise it seemed like the same thing and was a bit confusing). Arguably we could link direct to circuit.library at the top level, rather than circuit but I left things as they were for now.
=> Move methods into class pages for docs

.github/actions/install-finance/action.yml, .github/actions/install-main-dependencies/action.yml, .github/actions/run-tests/action.yml, .github/workflows/main.yml
Changed windows-2019 to windows-latest (current same as windows-2022) so it running on a newer version and use latest like is done on others. My recollection of it using windows-2019 specifically was when Aer was being built from source. As this is no longer the case it seems better to switch to a newer version and do -latest like is done with Ubuntu and Mac
I already did this in Nature https://github.com/qiskit-community/qiskit-nature/pull/1266 as part of updating CI there.
The branch rules will need updating to account for the job name change.
=> Update CI to use latest windows

test/data_providers/test_data_providers.py
From time to time the yahoo data provider unit test fails as the values fetched no longer match the reference values they were before. Maybe the historical data is compressed occasionally with a single value covering a larger time period so the value is altered a little for the average over that new period. Whatever the reason the nightly CI has failed the last couple of times due to some change in the ref values. This updates them, as had been done in the past, so its not the first time its happened! Since this will break unit tests over in stable I marked it as backport to keep them running if needed.
I also added a comment in the code to note this since it does need updating periodically.
=> Fix Yahoo Data Provider unit test

qiskit_finance/circuit/library/payoff_functions/european_call_pricing_objective.py, qiskit_finance/circuit/library/probability_distributions/lognormal.py, qiskit_finance/circuit/library/probability_distributions/normal.py, requirements.txt, test/circuit/test_probability_distributions.py
Nightly CI run failed last night following release of Qiskit 0.46. This PR updates the code around recent deprecations and changes to 0.46 and 1.0
* setup.py I bumped min version to 0.45 
* Use of qc.isometry has been deprecated so this uses Isometry and appends it
* Initialize moved out of qiskit.extensions (reason to bump min to 0.45)
* One test module inherited from QiskitTestCase and I change this to the local QiskitFinanceTestCase as test is no longer in Qiskit 1.0
* Updated `european call pricing objection` to use public data setter as setting it via _data, while that works up to 0.46, in 1.0 doing that  things no longer worked and threw an error about data.qubits not being there.
=> Fix compatibility/deprecations with newer Qiskit versions

README.md, docs/conf.py, docs/tutorials/00_amplitude_estimation.ipynb, docs/tutorials/01_portfolio_optimization.ipynb, docs/tutorials/02_portfolio_diversification.ipynb, qiskit_finance/__init__.py, qiskit_finance/data_providers/_base_data_provider.py, qiskit_finance/data_providers/data_on_demand_provider.py, qiskit_finance/data_providers/exchange_data_provider.py, qiskit_finance/data_providers/wikipedia_data_provider.py, qiskit_finance/data_providers/yahoo_data_provider.py, setup.py
Updates links away from qiskit.org to the new locations for the docs
Fixes #312
Fixes #313
Now that all the applications and the algorithms docs are deployed on github pages this updates the intersphinx links, in conf.py, and also urls that are coded directly in other places such as the readme and tutorials. I did not alter past release notes. There is a redirect now in effect for the former location on `qiskit.org/ecosystem` so they get to the right place.
Note that the current theme is still emitting a link to qiskit.org/ecosystem, but that will get redirected for now until such time as Qiskit/qiskit_sphinx_theme#588 is resolved and new docs are generated with such an updated theme and re-deployed.
=> Update intersphinx links and others

docs/tutorials/00_amplitude_estimation.ipynb, docs/tutorials/01_portfolio_optimization.ipynb, docs/tutorials/02_portfolio_diversification.ipynb, docs/tutorials/03_european_call_option_pricing.ipynb, docs/tutorials/04_european_put_option_pricing.ipynb, docs/tutorials/05_bull_spread_pricing.ipynb, docs/tutorials/06_basket_option_pricing.ipynb, docs/tutorials/07_asian_barrier_spread_pricing.ipynb, docs/tutorials/08_fixed_income_pricing.ipynb, docs/tutorials/09_credit_risk_analysis.ipynb, docs/tutorials/10_qgan_option_pricing.ipynb, docs/tutorials/11_time_series.ipynb, docs/tutorials/tutorial_magics.py
Qiskit 1,0 removed the deprecated qiskit.tools which included some .jupyter from which the magics that did the version and copyright were imported. This PR adds a local file in the tutorials folder that contains just these magics and changes the import to use this.
Similar fix to qiskit-community/qiskit-algorithms#156
=> Fix tutorials to work with Qiskit 1.0

.github/actions/install-main-dependencies/action.yml, .github/workflows/main.yml, releasenotes/notes/py_3_12_support-b61ebb772bc24cb8.yaml, setup.py, tox.ini
Closes #316
I marked this stable backport in order to facilitate a release that supports 3.12.
FYI: PR for Optimzation that adds the 3.12 support there qiskit-community/qiskit-optimization#580
Branch rules will need updating for this change.
Similar to #263 which added support for 3.11 where the Windows upper Python version needed to be restricted I have done the same here as `cvxpy` only has pre-built wheels for 3.11 and while Ubuntu and Mac are set for 3.12 this is because CI can build the wheels ok (as it does in Optimization) but that does not happen for Windows.
=> Add Python 3.12 support

.pylintdict, test/data_providers/test_data_providers.py
Nightly CI has been failing the last couple of nights. As happens on occasion the yahoo data provider data seems to have changed, maybe data gets compressed over time as more is added, so that the values are a bit different and fail some tests. This updates the test reference values to pass.
Also spell checker seems to be tripping up on transpiler. Not sure what happened there to change things, but I added that to custom dictionary.
=> Fix nightly CI failures

qiskit_finance/circuit/library/probability_distributions/normal.py, test/data_providers/test_data_providers.py
Closes #343
Now that the Qiskit issue referenced in  #343 has been released in 1.2.1 I have updated the failing data provider test reference values and also fixed the reference circuit draw output since that has changed too.
=> Fix CI for data provider change and cct draw

docs/conf.py, docs/getting_started.rst
The documentation source of truth is moving to https://quantum.cloud.ibm.com/.
=> Update intersphinx mapping and other URLs pointing to IQP Classic
